In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv("D:\Ml Models\Linear Regression\Dataset used\placement.csv")
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [10]:
df.head()

cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [6]:
X[:5]

array([[6.89],
       [5.12],
       [7.82],
       [7.42],
       [6.94]])

In [11]:
y[:5]


array([3.26, 1.98, 3.25, 3.67, 3.57])

In [26]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size = 0.2,
                                                    random_state = 2)

In [14]:
X_train[: 5]

array([[7.14],
       [8.93],
       [5.42],
       [5.1 ],
       [7.77]])

In [28]:
y_train[: 5]

array([3.13, 3.91, 2.25, 2.3 , 4.06])

In [33]:
from SimpleLinearRegression import simpleLinearRegression
reg = simpleLinearRegression()
reg.fit(X_train, y_train)

In [34]:
y_pred = reg.predict(X_test)

In [38]:

reg.fit(X_train, y_train)
compare = np.concatenate((y_pred.reshape(len(y_pred), 1),
                          y_test.reshape(len(y_test), 1)), 1)
compare[:5]

array([[3.89111601, 4.1       ],
       [3.09324469, 3.49      ],
       [2.38464568, 2.08      ],
       [2.57434935, 2.33      ],
       [1.6537286 , 1.94      ]])

In [40]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [42]:
print("MAE", mean_squared_error(y_test, y_pred))

MAE 0.12129235313495523


In [44]:
print("MSE", mean_squared_error(y_test, y_pred))

MSE 0.12129235313495523


In [46]:
print("R2 score", r2_score(y_test, y_pred))

R2 score 0.7807301475103842


In [47]:
print("RMSE", np.sqrt(mean_squared_error(y_test, y_pred)))

RMSE 0.3482705171773161
